# Generated by Django 2.1.1 on 2018-10-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqquotation',
            name='ReqDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqquotation',
            name='VendorReqDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
