# Generated by Django 2.1.1 on 2018-10-24 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0002_auto_20181024_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqquotation',
            name='ReqVendor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReqVendor2', to='MST.CoVendor'),
        ),
        migrations.AlterField(
            model_name='reqquotation',
            name='ReqVendor3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReqVendor3', to='MST.CoVendor'),
        ),
    ]
