# Generated by Django 2.1.1 on 2018-10-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0006_auto_20181024_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='Margin',
        ),
        migrations.AlterField(
            model_name='productlist',
            name='ProdStatus',
            field=models.CharField(choices=[('A', '운영중'), ('X', '단종')], max_length=1),
        ),
    ]
