# Generated by Django 2.1.1 on 2018-10-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0007_auto_20181024_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='AXRegDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
