# Generated by Django 2.1.1 on 2018-10-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0010_auto_20181024_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='ProdDiv',
            field=models.CharField(choices=[('DT', '데스크탑'), ('NT', '노트북'), ('MT', '모니터'), ('SR', '세단기'), ('ETC', '기타')], max_length=2),
        ),
    ]
