# Generated by Django 2.1.1 on 2018-10-25 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0011_auto_20181025_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='ProdCode',
        ),
    ]
