# Generated by Django 2.1.1 on 2018-10-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0012_remove_productlist_prodcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail_dt',
            name='ProdCode',
        ),
        migrations.RemoveField(
            model_name='productdetail_dt',
            name='RegUser',
        ),
        migrations.RemoveField(
            model_name='productdetail_dt',
            name='UpdateUser',
        ),
        migrations.RemoveField(
            model_name='productdetail_etc',
            name='ProdCode',
        ),
        migrations.RemoveField(
            model_name='productdetail_etc',
            name='RegUser',
        ),
        migrations.RemoveField(
            model_name='productdetail_etc',
            name='UpdateUser',
        ),
        migrations.RemoveField(
            model_name='productdetail_mt',
            name='ProdCode',
        ),
        migrations.RemoveField(
            model_name='productdetail_mt',
            name='RegUser',
        ),
        migrations.RemoveField(
            model_name='productdetail_mt',
            name='UpdateUser',
        ),
        migrations.RemoveField(
            model_name='productdetail_nt',
            name='ProdCode',
        ),
        migrations.RemoveField(
            model_name='productdetail_nt',
            name='RegUser',
        ),
        migrations.RemoveField(
            model_name='productdetail_nt',
            name='UpdateUser',
        ),
        migrations.RemoveField(
            model_name='productdetail_sr',
            name='ProdCode',
        ),
        migrations.RemoveField(
            model_name='productdetail_sr',
            name='RegUser',
        ),
        migrations.RemoveField(
            model_name='productdetail_sr',
            name='UpdateUser',
        ),
        migrations.AddField(
            model_name='productlist',
            name='CPU',
            field=models.CharField(blank=True, choices=[('1', '펜티엄'), ('3', '셀러론'), ('5', 'i3'), ('7', 'i5'), ('9', 'i7'), ('11', 'i9'), ('51', 'AMD'), ('99', '기타')], max_length=2),
        ),
        migrations.AddField(
            model_name='productlist',
            name='CPUDetail',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='productlist',
            name='DTType',
            field=models.CharField(blank=True, choices=[('T', '타워'), ('S', '슬림'), ('M', '미니'), ('E', '기타')], max_length=2),
        ),
        migrations.AddField(
            model_name='productlist',
            name='ETCType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productlist',
            name='GraphicCard',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='productlist',
            name='HDD',
            field=models.CharField(blank=True, choices=[('1', '500GB'), ('3', '1TB'), ('5', '2TB'), ('7', '3TB'), ('9', '4TB'), ('10', '4TB초과')], max_length=2),
        ),
        migrations.AddField(
            model_name='productlist',
            name='IORemark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productlist',
            name='Keyboard_YN',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='productlist',
            name='MTType',
            field=models.CharField(blank=True, choices=[('N', '일반'), ('C', '커브드')], max_length=2),
        ),
        migrations.AddField(
            model_name='productlist',
            name='Mouse_YN',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='productlist',
            name='NTBag_YN',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='productlist',
            name='NTPouch_YN',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='productlist',
            name='NTType',
            field=models.CharField(blank=True, choices=[('L', '보급'), ('M', '일반'), ('H', '고급'), ('G', '게이임')], max_length=2),
        ),
        migrations.AddField(
            model_name='productlist',
            name='Power',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='productlist',
            name='RAM',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='productlist',
            name='Ratio',
            field=models.CharField(blank=True, choices=[('1', '4:3'), ('3', '16:9'), ('5', '21:9')], max_length=2),
        ),
        migrations.AddField(
            model_name='productlist',
            name='SSD',
            field=models.CharField(blank=True, choices=[('1', '64GB'), ('2', '120GB'), ('3', '128GB'), ('4', '250GB'), ('5', '256GB'), ('6', '500GB'), ('7', '512GB'), ('8', '1TB'), ('9', '1TB초과')], max_length=2),
        ),
        migrations.AddField(
            model_name='productlist',
            name='ScreenSize',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='productlist',
            name='Weight',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='ProductDetail_DT',
        ),
        migrations.DeleteModel(
            name='ProductDetail_ETC',
        ),
        migrations.DeleteModel(
            name='ProductDetail_MT',
        ),
        migrations.DeleteModel(
            name='ProductDetail_NT',
        ),
        migrations.DeleteModel(
            name='ProductDetail_SR',
        ),
    ]
