# Generated by Django 2.1.1 on 2018-10-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0013_auto_20181025_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='HDD',
            field=models.CharField(blank=True, choices=[('0', 'None'), ('1', '500GB'), ('3', '1TB'), ('5', '2TB'), ('7', '3TB'), ('9', '4TB'), ('10', '4TB초과')], max_length=2),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='SSD',
            field=models.CharField(blank=True, choices=[('0', 'None'), ('1', '64GB'), ('2', '120GB'), ('3', '128GB'), ('4', '250GB'), ('5', '256GB'), ('6', '500GB'), ('7', '512GB'), ('8', '1TB'), ('9', '1TB초과')], max_length=2),
        ),
    ]
