# Generated by Django 2.1.1 on 2018-10-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0015_auto_20181025_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='Resolution',
            field=models.CharField(blank=True, choices=[('1', 'HD이하'), ('3', 'FHD(1920x1080)'), ('5', 'WFHD(2560x1080)'), ('7', 'WQHD(2560x1440)'), ('9', 'UWQHD(3440x1440)'), ('11', '4KUHD(3840x2160)'), ('13', '4KUHD초과')], max_length=2),
        ),
        migrations.AlterField(
            model_name='reqquotation',
            name='ShipDT',
            field=models.DateField(blank=True, null=True),
        ),
    ]
