# Generated by Django 2.1.1 on 2018-10-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0016_auto_20181025_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqquotation',
            name='ShipDT',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
