# Generated by Django 2.1.1 on 2018-10-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0017_auto_20181025_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqquotation',
            name='ShipDT',
            field=models.DateField(blank=True, null=True),
        ),
    ]
