# Generated by Django 2.1.1 on 2018-10-25 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0018_auto_20181025_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='ScreenSize',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='reqquotation',
            name='ReqDate',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 10, 25, 23, 59, 25, 61457), null=True),
        ),
    ]
