# Generated by Django 2.1.1 on 2018-10-26 00:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0019_auto_20181025_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqquotation',
            name='ReqDate',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 10, 26, 0, 1, 34, 477386, tzinfo=utc), null=True),
        ),
    ]
