# Generated by Django 2.1.1 on 2018-10-26 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0020_auto_20181026_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqquotation',
            name='ReqDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
