# Generated by Django 2.1.1 on 2018-11-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0024_auto_20181107_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='CPU',
            new_name='DTCPU',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='CPUDetail',
            new_name='DTCPUDetail',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='GraphicCard',
            new_name='DTGraphicCard',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='HDD',
            new_name='DTHDD',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='IORemark',
            new_name='DTIORemark',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='Mouse_YN',
            new_name='DTMouse_YN',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='Power',
            new_name='DTPower',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='RAM',
            new_name='DTRAM',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='SSD',
            new_name='DTSSD',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='ScreenSize',
            new_name='DTWeight',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='Weight',
            new_name='MTScreenSize',
        ),
        migrations.AddField(
            model_name='productlist',
            name='DTRemark',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='productlist',
            name='MTIORemark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productlist',
            name='MTRemark',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='productlist',
            name='MTWeight',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='productlist',
            name='NTCPU',
            field=models.CharField(blank=True, choices=[('1', '펜티엄'), ('3', '셀러론'), ('5', 'i3'), ('7', 'i5'), ('9', 'i7'), ('11', 'i9'), ('51', 'AMD'), ('99', '기타')], max_length=2),
        ),
        migrations.AddField(
            model_name='productlist',
            name='NTCPUDetail',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='productlist',
            name='NTGraphicCard',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='productlist',
            name='NTHDD',
            field=models.CharField(blank=True, choices=[('0', 'None'), ('1', '500GB'), ('3', '1TB'), ('5', '2TB'), ('7', '3TB'), ('9', '4TB'), ('10', '4TB초과')], max_length=2),
        ),
        migrations.AddField(
            model_name='productlist',
            name='NTIORemark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productlist',
            name='NTMouse_YN',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='productlist',
            name='NTRAM',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='productlist',
            name='NTRemark',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='productlist',
            name='NTSSD',
            field=models.CharField(blank=True, choices=[('0', 'None'), ('1', '64GB'), ('2', '120GB'), ('3', '128GB'), ('4', '250GB'), ('5', '256GB'), ('6', '500GB'), ('7', '512GB'), ('8', '1TB'), ('9', '2TB'), ('10', '2TB초과')], max_length=2),
        ),
        migrations.AddField(
            model_name='productlist',
            name='NTScreenSize',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='productlist',
            name='NTWeight',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='productlist',
            name='SRRemark',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
