# Generated by Django 2.1.1 on 2018-11-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0025_auto_20181107_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='Size',
        ),
    ]
