# Generated by Django 2.1.1 on 2018-11-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0026_remove_productlist_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='SRWeight',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
