# Generated by Django 2.1.1 on 2018-11-08 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0027_productlist_srweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqquotation',
            name='StatusA_Date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='reqquotation',
            name='StatusC_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqquotation',
            name='StatusF_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqquotation',
            name='StatusO_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqquotation',
            name='StatusR_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqquotation',
            name='StatusS_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='NTType',
            field=models.CharField(blank=True, choices=[('L', '보급'), ('M', '일반'), ('H', '고급'), ('G', '게이밍')], max_length=2),
        ),
    ]
