# Generated by Django 2.1.1 on 2018-11-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0029_remove_reqquotation_vendorreqdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqquotation',
            name='CanonETC',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
