# Generated by Django 2.1.1 on 2018-11-13 08:03

import Prod.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0030_auto_20181109_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqquotation',
            name='ReqNo',
            field=models.CharField(default=Prod.models.ReqQuotation.ReqNO_default, max_length=40),
        ),
    ]
