# Generated by Django 2.1.1 on 2018-11-14 05:11

import Prod.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0032_auto_20181113_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqquotation',
            name='ReqNo',
            field=models.CharField(default=Prod.models.ReqQuotation.ReqNO_default, max_length=30),
        ),
    ]
