# Generated by Django 2.1.1 on 2018-11-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0033_auto_20181114_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='DTRAM',
            field=models.CharField(blank=True, choices=[('1', '2GB이하'), ('2', '2-4GB'), ('3', '5-8GB'), ('4', '9-16GB'), ('5', '17-32GB'), ('6', '33-64GB이상')], default=2, max_length=1),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='NTRAM',
            field=models.CharField(blank=True, choices=[('1', '2GB이하'), ('2', '2-4GB'), ('3', '5-8GB'), ('4', '9-16GB'), ('5', '17-32GB'), ('6', '33-64GB이상')], default=2, max_length=1),
        ),
    ]
