# Generated by Django 2.1.1 on 2018-11-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0034_auto_20181115_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='DTRAM',
            field=models.CharField(blank=True, choices=[('1', '2GB'), ('2', '4GB'), ('3', '8GB'), ('4', '16GB'), ('5', '32GB'), ('6', '64GB')], default=2, max_length=1),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='NTRAM',
            field=models.CharField(blank=True, choices=[('1', '2GB'), ('2', '4GB'), ('3', '8GB'), ('4', '16GB'), ('5', '32GB'), ('6', '64GB')], default=2, max_length=1),
        ),
    ]
