# Generated by Django 2.1.1 on 2018-11-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0035_auto_20181115_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='DTGraphicCard',
            field=models.CharField(blank=True, default='내장', max_length=20),
        ),
    ]
