# Generated by Django 2.1.1 on 2018-11-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0037_auto_20181129_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqquotation',
            name='VendorReq_YN',
            field=models.BooleanField(default=False),
        ),
    ]
