# Generated by Django 2.1.1 on 2019-01-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0038_auto_20181129_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='DTOS',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productlist',
            name='NTOS',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productlist',
            name='Warranty',
            field=models.CharField(default='1년', max_length=5),
        ),
    ]
