# Generated by Django 2.1.1 on 2019-01-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prod', '0039_auto_20190110_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='ProdDiv',
            field=models.CharField(choices=[('DT', '데스크탑'), ('NT', '노트북'), ('MT', '모니터'), ('SR', '세단기'), ('ET', '기타')], max_length=2),
        ),
    ]
