# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default=12, max_length=254),
            preserve_default=False,
        ),
    ]
