# Generated by Django 2.1.1 on 2018-09-13 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptCode', models.CharField(max_length=7)),
                ('DeptName', models.CharField(max_length=20)),
                ('RegDate', models.DateField()),
                ('UpdateDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CoEmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpCode', models.CharField(max_length=6)),
                ('EmpName', models.CharField(max_length=20)),
                ('RegDate', models.DateField()),
                ('UpdateDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserType', models.CharField(max_length=1)),
                ('LastDate', models.DateField()),
                ('LoginIP', models.CharField(max_length=15)),
                ('LoginCount', models.IntegerField()),
                ('RegDate', models.DateField()),
                ('UpdateDate', models.DateField()),
                ('DeptCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MST.CoDept')),
                ('EmpNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MST.CoEmp')),
                ('RegUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoUser_RegUser', to='MST.CoUser')),
                ('UpdateUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoUser_UpdateUser', to='MST.CoUser')),
            ],
        ),
        migrations.CreateModel(
            name='CoVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VendorCode', models.CharField(max_length=7)),
                ('CompanyName', models.CharField(max_length=50)),
                ('Chief', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=100)),
                ('ComNumber', models.CharField(max_length=20)),
                ('ComTel', models.CharField(max_length=20)),
                ('Brand', models.CharField(max_length=30)),
                ('Major_YN', models.BooleanField()),
                ('ContactName1', models.CharField(max_length=30)),
                ('ContactTel1', models.CharField(max_length=30)),
                ('ContactCTel1', models.CharField(max_length=30)),
                ('ContactMail1', models.EmailField(max_length=254)),
                ('ContactName2', models.CharField(max_length=30)),
                ('ContactTel2', models.CharField(max_length=30)),
                ('ContactCTel2', models.CharField(max_length=30)),
                ('ContactMail2', models.EmailField(max_length=254)),
                ('AccountNo', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=1)),
                ('PaymentMethod', models.CharField(max_length=30)),
                ('PaymentPeriod', models.CharField(max_length=30)),
                ('Contract_YN', models.BooleanField()),
                ('ContractDate', models.DateField()),
                ('Remark', models.TextField()),
                ('ComPaper', models.FileField(upload_to='')),
                ('AccountPaper', models.FileField(upload_to='')),
                ('RegDate', models.DateField()),
                ('UpdateDate', models.DateField()),
                ('RegUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoVendor_RegUser', to='MST.CoUser')),
                ('UpdateUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoVendor_UpdateUser', to='MST.CoUser')),
            ],
        ),
        migrations.AddField(
            model_name='couser',
            name='VendorCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MST.CoVendor'),
        ),
        migrations.AddField(
            model_name='couser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coemp',
            name='RegUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoEmp_RegUser', to='MST.CoUser'),
        ),
        migrations.AddField(
            model_name='coemp',
            name='UpdateUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoEmp_UpdateUser', to='MST.CoUser'),
        ),
        migrations.AddField(
            model_name='codept',
            name='RegUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoDept_RegUser', to='MST.CoUser'),
        ),
        migrations.AddField(
            model_name='codept',
            name='UpdateUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoDept_UpdateUser', to='MST.CoUser'),
        ),
    ]
