# Generated by Django 2.1.1 on 2018-09-13 06:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdCode', models.CharField(max_length=10)),
                ('ProdDiv', models.CharField(max_length=2)),
                ('ProdName', models.CharField(max_length=50)),
                ('ProdBrand', models.CharField(max_length=20)),
                ('Mercury_YN', models.BooleanField()),
                ('AXProdCode', models.CharField(max_length=10)),
                ('AXProdName', models.CharField(max_length=50)),
                ('AXRegDate', models.DateField()),
                ('ProdStatus', models.CharField(max_length=1)),
                ('Basic_coprice', models.IntegerField()),
                ('Basic_price', models.IntegerField()),
                ('Margin', models.FloatField()),
                ('Inventory_YN', models.BooleanField()),
                ('Remark', models.TextField()),
                ('RegDate', models.DateField()),
                ('UpdateDate', models.DateField(default=datetime.date(2018, 9, 13))),
                ('RegUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prod_RegUser', to='MST.CoUser')),
                ('UpdateUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prod_UpdateUser', to='MST.CoUser')),
                ('VendorCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prod_Vendor', to='MST.CoVendor')),
            ],
        ),
        migrations.AlterField(
            model_name='coemp',
            name='UpdateDate',
            field=models.DateField(default=datetime.date(2018, 9, 13)),
        ),
    ]
