# Generated by Django 2.1.1 on 2018-09-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0003_auto_20180913_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='RegUser',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='UpdateUser',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='VendorCode',
        ),
        migrations.DeleteModel(
            name='ProductList',
        ),
    ]
