# Generated by Django 2.1.1 on 2018-09-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0004_auto_20180913_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covendor',
            name='RegDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='UpdateDate',
            field=models.DateField(auto_now=True),
        ),
    ]
