# Generated by Django 2.1.1 on 2018-10-18 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0006_auto_20180914_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codept',
            name='RegUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoDept_RegUser', to='MST.CoUser'),
        ),
        migrations.AlterField(
            model_name='codept',
            name='UpdateUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoDept_UpdateUser', to='MST.CoUser'),
        ),
        migrations.AlterField(
            model_name='coemp',
            name='RegUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoEmp_RegUser', to='MST.CoUser'),
        ),
        migrations.AlterField(
            model_name='coemp',
            name='UpdateUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoEmp_UpdateUser', to='MST.CoUser'),
        ),
        migrations.AlterField(
            model_name='couser',
            name='DeptCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MST.CoDept'),
        ),
        migrations.AlterField(
            model_name='couser',
            name='EmpNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MST.CoEmp'),
        ),
        migrations.AlterField(
            model_name='couser',
            name='LastDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='couser',
            name='LoginCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='couser',
            name='LoginIP',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='couser',
            name='RegUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoUser_RegUser', to='MST.CoUser'),
        ),
        migrations.AlterField(
            model_name='couser',
            name='UpdateUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoUser_UpdateUser', to='MST.CoUser'),
        ),
        migrations.AlterField(
            model_name='couser',
            name='VendorCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MST.CoVendor'),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='AccountNo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='AccountPaper',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='ComPaper',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='ContactCTel2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='ContactMail2',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='ContactName2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='ContactTel2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='ContractDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='Contract_YN',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='PaymentMethod',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='PaymentPeriod',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='Remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='VendorCode',
            field=models.CharField(default='V', max_length=7),
        ),
    ]
