# Generated by Django 2.1.1 on 2018-10-18 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0007_auto_20181018_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codept',
            name='RegUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoDept_RegUser', to='MST.CoUser'),
        ),
        migrations.AlterField(
            model_name='codept',
            name='UpdateUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoDept_UpdateUser', to='MST.CoUser'),
        ),
        migrations.AlterField(
            model_name='coemp',
            name='RegUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoEmp_RegUser', to='MST.CoUser'),
        ),
        migrations.AlterField(
            model_name='coemp',
            name='UpdateUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoEmp_UpdateUser', to='MST.CoUser'),
        ),
        migrations.AlterField(
            model_name='couser',
            name='RegUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoUser_RegUser', to='MST.CoUser'),
        ),
        migrations.AlterField(
            model_name='couser',
            name='UpdateUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoUser_UpdateUser', to='MST.CoUser'),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='RegUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoVendor_RegUser', to='MST.CoUser'),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='UpdateUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoVendor_UpdateUser', to='MST.CoUser'),
        ),
    ]
