# Generated by Django 2.1.1 on 2018-10-18 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0008_auto_20181018_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couser',
            name='DeptCode',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoDept', to='MST.CoDept'),
        ),
        migrations.AlterField(
            model_name='couser',
            name='EmpNo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MST.CoEmp'),
        ),
        migrations.AlterField(
            model_name='couser',
            name='VendorCode',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MST.CoVendor'),
        ),
    ]
