# Generated by Django 2.1.1 on 2018-10-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0010_auto_20181018_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='couser',
            name='UserName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
