# Generated by Django 2.1.1 on 2018-10-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0011_couser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='coemp',
            name='Dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoEmp_Dept', to='MST.CoDept'),
        ),
    ]
