# Generated by Django 2.1.1 on 2018-10-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0012_coemp_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couser',
            name='DeptCode',
        ),
    ]
