# Generated by Django 2.1.1 on 2018-10-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0013_remove_couser_deptcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covendor',
            name='AccountNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='AccountPaper',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='ComPaper',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='ContactCTel2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='ContactMail2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='ContactName2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='ContactTel2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='ContractDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='Contract_YN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='PaymentMethod',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='PaymentPeriod',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='Remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
