# Generated by Django 2.1.1 on 2018-10-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0014_auto_20181018_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covendor',
            name='AccountPaper',
            field=models.FileField(blank=True, null=True, upload_to='vendor'),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='ComPaper',
            field=models.FileField(blank=True, null=True, upload_to='vendor'),
        ),
    ]
