# Generated by Django 2.1.1 on 2018-10-22 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0015_auto_20181018_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covendor',
            name='VendorCode',
        ),
    ]
