# Generated by Django 2.1.1 on 2018-10-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0016_remove_covendor_vendorcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covendor',
            name='Status',
            field=models.CharField(choices=[('1', '거래중'), ('9', '종료')], max_length=1),
        ),
    ]
