# Generated by Django 2.1.1 on 2018-11-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0017_auto_20181026_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covendor',
            name='Contract_YN',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='covendor',
            name='Major_YN',
            field=models.BooleanField(default=False),
        ),
    ]
