# Generated by Django 2.1.1 on 2018-11-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0018_auto_20181101_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covendor',
            name='Status',
            field=models.CharField(choices=[('1', '거래중'), ('9', '종료')], default=1, max_length=1),
        ),
    ]
