# Generated by Django 2.1.1 on 2018-11-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0019_auto_20181101_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covendor',
            name='ComNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
