# Generated by Django 2.1.1 on 2018-11-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0020_auto_20181102_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covendor',
            name='ComNumber',
            field=models.CharField(max_length=20),
        ),
    ]
