# Generated by Django 2.1.1 on 2018-11-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0021_auto_20181102_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covendor',
            name='ComNumber',
            field=models.CharField(error_messages={'unique': '동일한 사업자 번호가 존재합니다.'}, max_length=20, unique=True),
        ),
    ]
