# Generated by Django 2.1.1 on 2018-11-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0022_auto_20181102_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couser',
            name='UserType',
            field=models.CharField(choices=[('A', '관리자'), ('I', 'ITS담당'), ('M', 'ITS관리자'), ('S', '영업사원'), ('V', '벤더')], max_length=1),
        ),
    ]
