# Generated by Django 2.1.1 on 2018-12-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0023_auto_20181109_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='couser',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='couser',
            name='Phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
