# Generated by Django 2.1.1 on 2019-01-31 02:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0024_auto_20181211_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoDevBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuDiv', models.CharField(choices=[('0', '기본관리'), ('1', '견적관리'), ('2', '발주관리'), ('3', '손익관리'), ('4', '진도관리'), ('5', '기타'), ('C', '공통관리')], max_length=20)),
                ('MenuName', models.CharField(max_length=50)),
                ('RequestName', models.CharField(max_length=50)),
                ('RequestDetail', models.TextField()),
                ('ReqDate', models.DateField(default=django.utils.timezone.now)),
                ('Status', models.CharField(choices=[('R', '요청'), ('A', '접수'), ('I', '수정중'), ('C', '수정완료')], max_length=10)),
                ('Priority', models.CharField(choices=[('1', '상'), ('5', '중'), ('9', '하')], max_length=5)),
                ('Difficulty', models.CharField(choices=[('1', '상'), ('5', '중'), ('9', '하')], max_length=5)),
                ('RegDate', models.DateField(auto_now_add=True)),
                ('UpdateDate', models.DateField(auto_now=True)),
                ('ReqUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoEmp_ReqUser', to='MST.CoUser')),
            ],
        ),
        migrations.CreateModel(
            name='CoDevBoardReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReplyDetail', models.TextField()),
                ('RegDate', models.DateField(auto_now_add=True)),
                ('Version', models.CharField(blank=True, max_length=20, null=True)),
                ('CoDevBoard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoDevBoardReply_Board', to='MST.CoDevBoard')),
                ('RegUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoDevBoardReply_RegUser', to='MST.CoUser')),
            ],
        ),
    ]
