# Generated by Django 2.1.1 on 2018-12-10 07:23

import Order.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Prod', '0038_auto_20181129_1609'),
        ('MST', '0023_auto_20181109_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfferNo', models.CharField(default=Order.models.OfferPrice.OfferNO_default, max_length=20)),
                ('OriginOfferNO', models.CharField(blank=True, max_length=20)),
                ('OfferDate', models.DateField(default=django.utils.timezone.now)),
                ('OfferResult', models.CharField(choices=[('S', '제안'), ('O', '발주'), ('C', '변경'), ('F', '실패')], default='S', max_length=5)),
                ('PONumber', models.CharField(blank=True, max_length=10)),
                ('SignNumber', models.CharField(blank=True, max_length=10)),
                ('Acceptance_YN', models.BooleanField(default=False)),
                ('AcceptanceDate', models.DateField(blank=True, null=True)),
                ('AcceptanceFile', models.FileField(blank=True, upload_to='')),
                ('Quotation', models.FileField(blank=True, upload_to='')),
                ('RegDate', models.DateField(auto_now_add=True, null=True)),
                ('UpdateDate', models.DateField(auto_now=True, null=True)),
                ('ReqNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Offer_ReqNO', to='Prod.ReqQuotation')),
                ('ReqUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Offer_RegUser', to='MST.CoUser')),
                ('UpdateUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Offer_UpdateUser', to='MST.CoUser')),
            ],
        ),
        migrations.CreateModel(
            name='OfferPriceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField()),
                ('CoPrice', models.IntegerField()),
                ('OfferPrice', models.IntegerField()),
                ('Address', models.CharField(default='', max_length=500)),
                ('ContactPerson', models.CharField(default='', max_length=50)),
                ('ContactTel', models.CharField(default='', max_length=50)),
                ('ReleaseDate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('DeliveryTempDate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('DeliveryDate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('LogiType', models.CharField(blank=True, choices=[('D', '직배송'), ('L', '택배')], max_length=4)),
                ('LogiCompany', models.CharField(blank=True, choices=[('1', 'CJ대한통운'), ('2', '우체국택배'), ('3', '한진택배'), ('4', '롯데택배'), ('5', '로젠택배'), ('6', '경동택배')], max_length=4)),
                ('LogiNo', models.CharField(blank=True, max_length=50)),
                ('OfferNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Offer_No', to='Order.OfferPrice')),
                ('ProdCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Offer_Prod', to='Prod.ProductList')),
            ],
        ),
    ]
