# Generated by Django 2.1.1 on 2018-12-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerpricedetail',
            name='Address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='offerpricedetail',
            name='ContactPerson',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='offerpricedetail',
            name='ContactTel',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
