# Generated by Django 2.1.1 on 2018-12-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_offerprice_orderdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerprice',
            name='AcceptanceDate',
        ),
        migrations.RemoveField(
            model_name='offerprice',
            name='AcceptanceFile',
        ),
        migrations.RemoveField(
            model_name='offerprice',
            name='Acceptance_YN',
        ),
        migrations.RemoveField(
            model_name='offerpricedetail',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='offerpricedetail',
            name='ContactPerson',
        ),
        migrations.RemoveField(
            model_name='offerpricedetail',
            name='ContactTel',
        ),
        migrations.RemoveField(
            model_name='offerpricedetail',
            name='DeliveryTempDate',
        ),
        migrations.RemoveField(
            model_name='offerpricedetail',
            name='ReleaseDate',
        ),
        migrations.AlterField(
            model_name='offerpricedetail',
            name='DeliveryDate',
            field=models.DateField(blank=True),
        ),
    ]
