# Generated by Django 2.1.1 on 2018-12-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_auto_20181212_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerpricedetail',
            name='DeliveryDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
