# Generated by Django 2.1.1 on 2018-12-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_auto_20181212_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerprice',
            name='ClosingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerpricedetail',
            name='LogiType',
            field=models.CharField(blank=True, choices=[('D', '직배송'), ('L', '택배'), ('S', '상동')], max_length=4),
        ),
    ]
