# Generated by Django 2.1.1 on 2018-12-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_auto_20181212_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerprice',
            name='PZNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
