# Generated by Django 2.1.1 on 2018-12-13 02:22

import Order.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MST', '0024_auto_20181211_1437'),
        ('Prod', '0038_auto_20181129_1609'),
        ('Order', '0008_offerprice_pznumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RentalNo', models.CharField(default=Order.models.RentalList.RentalNo_default, max_length=20)),
                ('RentalType', models.CharField(choices=[('S', '매출'), ('R', '재렌탈')], default='S', max_length=1)),
                ('RentalStatus', models.CharField(choices=[('I', '진행'), ('R', '만료'), ('S', '중도해지')], default='I', max_length=1)),
                ('Custname', models.CharField(max_length=100)),
                ('RentalStartDate', models.DateField()),
                ('RentalEndDate', models.DateField()),
                ('RentalQty', models.IntegerField()),
                ('RentalCoPrice', models.IntegerField()),
                ('RentalOfferPrice', models.IntegerField()),
                ('RegDate', models.DateField(auto_now_add=True, null=True)),
                ('UpdateDate', models.DateField(auto_now=True, null=True)),
                ('DeptCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rental_Dept', to='MST.CoDept')),
                ('EmpNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rental_Emp', to='MST.CoEmp')),
                ('RentalProdCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rental_Prod', to='Prod.ProductList')),
                ('RentalVendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RentalVendor', to='MST.CoVendor')),
                ('ReqUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rental_RegUser', to='MST.CoUser')),
                ('UpdateUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rental_UpdateUser', to='MST.CoUser')),
            ],
        ),
    ]
