# Generated by Django 2.1.1 on 2018-12-13 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_rentallist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentallist',
            name='RentalVendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RentalVendor', to='MST.CoVendor'),
        ),
    ]
