# Generated by Django 2.1.1 on 2018-12-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_auto_20181213_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentallist',
            name='RentalEndDate',
        ),
        migrations.AddField(
            model_name='rentallist',
            name='RentalPeriod',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rentallist',
            name='RentalStatus',
            field=models.CharField(choices=[('I', '진행중'), ('R', '만료'), ('S', '중도해지')], default='I', max_length=1),
        ),
    ]
