# Generated by Django 2.1.1 on 2019-01-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_auto_20181213_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerpricedetail',
            name='SerialNumber',
            field=models.TextField(blank=True, null=True),
        ),
    ]
